### PR TITLE
setting up _targets.R, following issue #6

### PR DESCRIPTION
**Pull request by elmeraa-usgs**
### Overview
Following along with issue #6, I concatinated ```_targets.R```

### Summary
- Here, I added the ```_targets.R``` script which contains code provided in issue #6.

### CODE REVIEW

**Comment by elmeraa-usgs** [comment]
### Overview
Following along with issue #6, I updated the ```_targets.R``` makefile to create the ```figure_1.png``` viz. This required editing the function scripts to return their relative path to output files. Updated ```.gitignore``` as well.

### Summary
-  I updated the ```_targets.R``` makefile to source functions, and adjusted the code to input and/or output data to the appropriate phase folders. 
- updated the function scripts to include ```return(file_out)``` following Julie's note that ```format = "file"``` should save the file and return a character string that contains the relative path to the file.
- updated the ```.gitignore``` file so it does not track the contents of the targets directory & ignores the ```1_fetch/out``` contents so we don't store changes to the downloaded ```.csv``` file. 

targets

**Comment by padilla410** [comment]
Ok! Nice job here, but I have one correction: I found a lingering bug from your first PR that I did not catch the first time. Since it is not included in the `diff` I cannot directly comment on it, so I'll address it here: 

[This line](https://github.com/elmeraa/ds-pipelines-targets-1/blob/af38ab55a6bb5c869a378bb8314f3712cad1f251/1_fetch/src/fetch.R#L8) prevents your pipeline from running successfully in a freshly cloned repo. I'm going to keep it a little vague on purpose, so you can give some thought to the "why". What I will say is that is that it could be a one or two line fix that involves a regular expression (which I can see [you are already familiar with](https://github.com/elmeraa/ds-pipelines-targets-1/blob/4887adb13a956a0f1a25b15f4887e5e9b2827c1f/3_visualize/src/diagnostics.R#L37)). Once I made this fix, the pipeline ran without a problem.

This mod applies to all of your functions that check for `out` directories:
* fetch
* process
* visualize
* diagnostics

Bonus resources: I often use this website: https://regex101.com/ when trying to come up with an appropriate regex. It doesn't map perfectly to R, but it gets you close.

**Comment by elmeraa-usgs** [comment]
Thanks, Julie. I see what you mean here. Freshly cloned repo's won't have the existence of ```out``` subfolders. Here, I went ahead and updated the subfolder check code using ```lapply()```, where if the subfolder already exists, it returns ```false``` and if the subfolder does not exist, it will create the subfolder using a paste command from ```getwd()``` and the appropriate phase folder. Is this what you had in mind?

**Comment by padilla410** [comment]
Howdy Elmera,

Your logic described above is correct, but the execution needs a tweak. There are three things going on in the code:

1. You don't need an `lapply` because you are not iterating over anything. These two snippets have the same result:
```r
file_out <- '2_process/out/model_summary_results.csv'

# your code
lapply(file_out, 
       function(x) 
         if(!dir.exists(x)) dir.create(paste(getwd(), "2_process", "out", sep = "/"))) 

# a simplified approach
if(!dir.exists(file_out)) dir.create(paste(getwd(), "2_process", "out", sep = "/"))
```

2. Using your current approach, `!dir.exists(x)` will always return `TRUE` because `file_out` contains a directory and a file name. and a warning every time you run the pipeline.

Here's the warning I get: 
```r
Warning message:
In dir.create(paste(getwd(), "2_process", "out", sep = "/")) :
  'C:\Users\jpadilla\Documents\projects\Training\onboarding\elmera\ds-pipelines-targets-1\2_process\out' already exists
```
Here is verification of what I described above:
```r
# run this
file.exists(file_out)
dir.exists(file_out)

# results 
> file.exists(file_out)
[1] TRUE
> dir.exists(file_out)
[1] FALSE
```
3. Finally, the call to `getwd()` is not necessary. When you're working in an Rproject you only need relative filepaths, so you could use `dir.create(paste("2_process", "out", sep = "/")` instead of `dir.create(paste(getwd(), "2_process", "out", sep = "/")`

So, what you need to do is remove the file name from `file_out` so that you are checking for `2_process/out/` and not `2_process/out/model_summary_results.csv`. This snippet `if(!dir.exists(file_out)) dir.create(paste("2_process", "out", sep = "/"))` is good, but you are checking for the wrong thing. To accomplish this I would like you to use the `stringr` package and the following regular expression: `'^[^\/]*\/[^\/]*'`. Here's a rough translation of what that regular expression means:
* `^` - start looking at the start of a string
* `[^\/]*` - match everything before the first forward slash (the `\` is an escape character)
* `\/` - match the first forward slash
* `[^\/]*` - match everything before the second forward slash
You can play around with this for yourself at https://regex101.com/

Apply this change across all your functions and then we should be ready to roll.

**Comment by padilla410** [comment]
Ok! It runs! I approve! Go ahead and merge when you're ready.

**Pull request merged**
